services:
  - type: web
    name: gabriella-noack-campaign
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /200.html
